# Data from Google Sheets
https://docs.google.com/spreadsheets/d/1npHtJlhs-ai7RBWqnDq5Cs7uCgVeIpOZRqPYf0K-WHk/edit#gid=0

In [43]:
# Libraries
import pandas as pd
sheet_id = '1npHtJlhs-ai7RBWqnDq5Cs7uCgVeIpOZRqPYf0K-WHk'
sheet_name = 'student1'

url1 = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
print(url1)
#pd.read_csv(url)
#sheet should have public access with link

https://docs.google.com/spreadsheets/d/1npHtJlhs-ai7RBWqnDq5Cs7uCgVeIpOZRqPYf0K-WHk/gviz/tq?tqx=out:csv&sheet=student1

In [39]:
data1 = pd.read_csv(url1, )

In [40]:
data1.head()

,rollno,sname,feepaid,gender,cat,dob,age,class10,class12,sem1,...,java,dbms,dwm,vlsi,cpp,cbnst,btechmarks,finalgrade,btechfinal,cgpa
0,102052,student49,35800,M,GEN,5-Apr-91,21,71,First,56,...,85,72,67,40,72,56,68,A,Pass,9
1,102035,student31,35800,M,OBC,19-Dec-92,20,57,First,77,...,76,58,50,65,50,64,63,A,Pass,9
2,102049,student44,35800,M,SC,11-May-93,19,50,Third,61,...,65,65,48,35,45,35,35,C,Fail,3
3,102002,student2,35800,M,GEN,24-Jul-93,19,78,First,67,...,92,45,63,63,62,40,69,A,Pass,9
4,102036,student32,35800,F,GEN,19-Sep-93,19,68,First,61,...,89,58,63,70,83,41,68,A,Pass,9

In [41]:
data1B = pd.read_csv(url1, parse_dates=['dob'])
# index_col=0, parse_dates=['dateCol']

In [42]:
print(data1B.iloc[1:5,1:5])
print(data1B.dtypes)

       sname  feepaid gender  cat
1  student31    35800      M  OBC
2  student44    35800      M   SC
3   student2    35800      M  GEN
4  student32    35800      F  GEN
rollno                 int64
sname                 object
feepaid                int64
gender                object
cat                   object
dob           datetime64[ns]
age                    int64
class10                int64
class12               object
sem1                   int64
sem2                   int64
attnd                float64
batch                 object
batchyr                int64
br                    object
city                  object
java                   int64
dbms                   int64
dwm                    int64
vlsi                   int64
cpp                    int64
cbnst                  int64
btechmarks             int64
finalgrade            object
btechfinal            object
cgpa                   int64
dtype: object

In [ ]:
data1C.head()

## Method2
- this works with API Access
https://docs.gspread.org/en/latest/
#!pip install gspread

## Method 3
- Not working
#%%% https://pypi.org/project/gsheets/
#!pip install gsheets
from gsheets import Sheets